version: "3"
services:
  frontend:
    image: flavor-fusionator-frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    environment:
      - ENV_VARIABLE=${ENV_VARIABLE}
    env_file:
      - ./frontend/.env
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.frontend.rule=Host("flavor-fusionator.localhost")'
      - "traefik.http.routers.frontend.entrypoints=web"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
  backend:
    image: flavor-fusionator-backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/flavor-fusionator
    env_file:
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.backend.rule=(Host("flavor-fusionator.localhost") && (PathPrefix(`/api`) || PathPrefix(`/socket`)))'
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix@docker"
      - "traefik.http.routers.backend.entrypoints=web"
    ports:
      - 3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
  mongo:
    image: mongo
    ports:
      - 37017:27017
  load-balancer:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
